#!/bin/sh

trap goodbye INT HUP

usage() {
	echo "Smail v0.1.0: Send emails from your terminal using a very simple SMTP client."
	echo ""
	echo "Usage: smail [options] [command]"
	echo ""
	echo "Options:"
	echo "  -v		verbose output"
	echo "  -h		show this help"
	echo "  --help		show this help"
	echo "  --version	show version info"
	echo ""
	echo "Commands:"
	echo "  send		runs the send email interface, default"
	echo "  config		runs the configuration script, also on first run"
	echo "  help		show this help"
	echo ""
	echo "Examples:"
	echo "  smail config	Run the configuration script"
	echo "  smail		Send an email"
	echo ""
	echo "Report bugs to: bleemayer@gmail.com"
	echo "Home page: <https://www.github.com/blmayer/smail/>"
	echo "General help: <https://www.github.com/blmayer/smail/wiki>"
}

show_version() {
	echo "smail 0.1.0"
	echo "Copyright (C) 2020 Brian Mayer."
	#echo "License MIT: MIT License <https://opensource.org/licenses/MIT>"
	echo "THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,"
	echo "EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF"
	echo "MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT."
	echo ""
	echo "Written by Brian Lee Mayer."
}

goodbye() {
	[ -e "$debug" ] || echo Quitting
	case $state in
		1|2|3|6|7|8)
			[ -e "$debug" ] || echo "Sending quit command"
			echo rset > .in
			echo quit > .in
			;;
		4|5)
			[ -e "$debug" ] || echo "Dropping and sending quit command"
			echo "" > .in
			echo rset > .in
			echo quit > .in
			;;
		9)
			[ -e "$debug" ] || echo "Erasing .temp and sending quit command"
			rm .temp
			echo rset > .in
			echo quit > .in
			exit 3
			;;
		10)
			echo quit > .in
			;;
		*)
			exit 2
			;;
	esac

	rm .in .out
	exit 0
}

read_opts() {
	for arg in "$@"
	do
		case $arg in
			"-v")
				debug=1
				;;
			"-h" | "help" | "--help")
				usage
				exit 0
				;;
			"--version")
				show_version
				exit 0
				;;
			"send")
				;;
			"config")
				configure
				exit 0
				;;
			"")
				break
				;;
			*)
				echo Unrecognized option
				usage
				exit 1
				;;
		esac
	done
}

configure() {
	echo "Running configuration"
	[ -e "$HOME/.config/smail" ] || mkdir -p "$HOME/.config/smail"

	echo "Enter email:"
	read -r username
	echo "email=$(echo "$username" | base64 )" > "$configfile"

	echo "Enter password:"
	stty -echo
	read -r password
	stty echo
	echo "password=$(echo "$password" | base64 )" >> "$configfile"

	echo "Enter your favorite editor: [vi]"
	# shellcheck disable=SC2039
	read -re editor
	echo "editor=${editor:-vi}" >> "$configfile"
	echo Done
}

connect() {
	openssl s_client -quiet \
		-starttls smtp \
		-connect smtp.gmail.com:587 \
		-crlf < .in > .out 2> /dev/null &
	state=1

	[ -e $debug ] || echo "Sending client hello"
	echo ehlo smtp.gmail.com > .in
	state=2
}

add_attachments() {
	echo "Enter file path:"
	# shellcheck disable=SC2039,SC2162
	read -e annex
	if [ -f "$annex" ]; then
		echo "Enter attachment name: [$(basename "$annex")]"
		read -r annexname
		[ "$annexname" = "" ] && annexname="$(basename "$annex")"

		{
			echo "Content-Type: application/octet-stream"
			echo "Content-Transfer-Encoding: base64"
			echo "Content-Disposition: attachment;"
			echo " filename= \"$annexname\""
			echo ""
		} >> .temp
		base64 "$annex" >> .temp
		[ -e $debug ] || echo "Added $annex with name: $annexname"
	else
		echo "ERROR: File not found!"
	fi

	echo "Add another attachment(s)? [y/N]"
	read -r another
	[ "$another" = "y" ] && { echo "--$1" >> .temp; add_attachments "$1"; }
}

get_rcpt() {
	echo "$to" | cut -d ',' -f "$1"
}

compose() {
	echo "Type recipient(s) (comma separated):"
	read -r to

	echo "To: $to" > .temp
	echo "From: $emaildec" >> .temp

	echo "Type Cc(s): (comma separated)"
	read -r cc
	[ -n "$cc" ] && { echo "Cc: $cc" >> .temp; to="$to,$cc"; }

	echo "Type Cco(s): (comma separated)"
	read -r cco
	[ -n "$cco" ] && { echo "Cco: $cco" >> .temp; to="$to,$cco"; }

	# Transform into list for sending later
	n=$(($(echo "$to" | tr -d -c ',' | wc -c | xargs) + 1))

	echo "Type subject:"
	read -r subj
	echo "Subject: $subj" >> .temp
	[ -e $debug ] || echo "Email fields:"
	[ -e $debug ] || cat .temp

	boundary="$(date | tr " :-" "wUX")"
	{
		echo "MIME-Version: 1.0"
		echo "Content-Type: multipart/mixed;"
		echo " boundary= \"$boundary\""
		echo ""
	
		echo "--$boundary"
		echo 'Content-Type: text/plain; charset=US-ASCII'
		echo ""
	} >> .temp

	$editor .body
	sed 's/^.$/../' .body | fold -w 72 -s >> .temp
	[ -e $debug ] || echo "Email body:"
	[ -e $debug ] || cat .body
	rm .body

	echo "" >> .temp
	echo "--$boundary" >> .temp

	echo "Insert attachment(s)? [y/N]"
	read -r attach
	[ "$attach" = "y" ] && add_attachments "$boundary"

	echo "--$boundary--" >> .temp
}

retry() {
	echo Retrying...
	case $state in
		2)
			[ -e $debug ] || echo "Reconnecting..."
			echo ehlo smtp.gmail.com > .in
			;;
		3)
			[ -e $debug ] || echo "Logging in again..."
			echo auth login > .in
			;;
		4)
			[ -e $debug ] || echo "Resending email"
			echo "$email" > .in
			;;
		5)
			[ -e $debug ] || echo "Resending password"
			echo "$password" > .in
			;;
		6)
			[ -e $debug ] || echo "Resending mail command"
			echo 'mail from: <'"$emaildec"'>' > .in
			;;
		7)
			[ -e $debug ] || echo "Resending recipient"
			echo rcpt to: '<'"$to"'>' > .in
			;;
		8)
			[ -e $debug ] || echo "Resending data command"
			echo data > .in
			;;
		9)
			[ -e $debug ] || echo "Resending data"
			cat .temp > .in
			echo '.' > .in
			;;
	esac
}

send() {
	while :
	do
		read -r msg < .out
		[ -e $debug ] || echo "received: $msg"
		case $msg in
			"221 2.0.0"*)
				retry
				;;

			"250-"*)
				;;

			"250 SMTPUTF8"*)
				[ -e $debug ] || echo logging in
				state=3
				echo auth login > .in
				;;

			"334 VXNlcm5hbWU6"*)
				[ -e $debug ] || echo sending email
				state=4
				echo "$email" > .in
				;;

			"334 UGFzc3dvcmQ6"*)
				[ -e $debug ] || echo sending password
				state=5
				echo "$password" > .in
				;;

			"235 2.7.0"*)
				[ -e $debug ] || { echo logged in; echo "$emaildec"; }
				state=6
				echo 'mail from: <'"$emaildec"'>' > .in
				;;

			"250 2.0.0"*)
				state=10
				rm .temp
				break
				;;

			"250 2.1.0"*)
				[ -e "$debug" ] || get_rcpt "$n"
				state=7
				echo rcpt to: '<'"$(get_rcpt $n)"'>' > .in
				n=$((n - 1))
				;;

			"250 2.1.5"*)
				if [ ! $n = 0 ]
				then
					[ -e $debug ] || get_rcpt "$n"
					echo rcpt to: '<'"$(get_rcpt $n)"'>' > .in
					n=$((n - 1))
				else
					[ -e $debug ] || echo data
					state=8
					echo data > .in
				fi
				;;

			"354  Go ahead"*)
				state=9
				cat .temp > .in
				echo '.' > .in
				;;

			"451 4.4.2 Timeout"*)
				[ -e $debug ] || echo "Connection closed"
				break
				;;

			"501 5.5.2 Cannot Decode response"*)
				state=3
				retry
				;;
			"502 5.5.1 Unrecognized command"*)
				retry
				;;
			"503 5.5.1 MAIL first"*)
				state=6
				retry
				;;
			"530-5.7.0"*)
				;;
			"530 5.7.0"*)
				state=3
				retry
				;;
			"535 5.7.8"*)
				state=3
				retry
				;;
			"553 5.1.3"*)
				retry
				;;
			"554 5.7.0"*)
				break
				;;
			"555 5.5.2 Syntax error"*)
				echo FATAL ERROR email not sent
				break
				;;
			*)
				[ -e $debug ] || echo "Unrecognized message"
				break
				;;
		esac
	done
}

# Read arguments
configfile="$HOME/.config/smail/smail.conf"
read_opts "$@"

# Configuration step
[ -e "$configfile" ] || configure

email=$(grep email "$configfile" | cut -d '=' -f 2)
emaildec=$(echo "$email" | base64 -d)
password=$(grep password "$configfile" | cut -d '=' -f 2)
editor=$(grep editor "$configfile" | cut -d '=' -f 2)

[ -p .in ] || mkfifo .in;
[ -p .out ] || mkfifo .out;

state=0

compose
connect
send
goodbye

